log in2.log
units lj
dimension 3
boundary p p p

atom_style molecular
neighbor 0.3 bin
neigh_modify delay 4 every 2
comm_modify vel yes

read_data pol.data


region  water  cylinder x 0 0 6 INF INF
create_atoms 3 random 21792 2021 water

#fix 1 all property/atom d_rho
compute 10 all sph/rho/atom


group 1 type 1
group 2 type 2
group 3 type 3
group 4 type 4
group water type 5
group membrane type 1:4
group all union water membrane

bond_style harmonic
bond_coeff 1 200 0.45
#bond_coeff 2 200 0.40

#angle_style harmonic
#angle_coeff 1 2 180
#angle_coeff 2 2 180
#angle_coeff 3 2 120
#angle_coeff 4 2 100
#angle_coeff 5 2 180
#angle_coeff 6 2 180
#angle_coeff 7 2 180
#angle_coeff 8 2 180
#angle_coeff 9 2 120
#angle_coeff 10 2 180
#angle_coeff 11 2 180
#angle_coeff 12 2 180
#angle_coeff 13 2 180

pair_style hybrid/overlay mdpd/rhosum mdpd 1.0 1.0 65689
pair_coeff  *  *   mdpd/rhosum  0.75
#pair_coeff  4  4   mdpd  -23.0  25.0  4.5  1.0  0.75
#pair_coeff  5  5   mdpd  -50.0  25.0  4.5  1.0  0.75
#pair_coeff  4  5   mdpd  -26.0  25.0  4.5  1.0  0.75
#pair_coeff 1*2 5   mdpd  -51.0  25.0  4.5  1.0  0.75
#pair_coeff  3  5   mdpd  -48.0  25.0  4.5  1.0  0.75
#pair_coeff  1  1   mdpd  -37.0  25.0  4.5  1.0  0.75
#pair_coeff  1  2   mdpd  -37.0  25.0  4.5  1.0  0.75
#pair_coeff  2  2   mdpd  -37.0  25.0  4.5  1.0  0.75
#pair_coeff 1*2 3   mdpd  -34.0  25.0  4.5  1.0  0.75
#pair_coeff  3  3   mdpd  -34.0  25.0  4.5  1.0  0.75
#pair_coeff 1*2 4   mdpd  -30.0  25.0  4.5  1.0  0.75
#pair_coeff  3  4   mdpd  -27.0  25.0  4.5  1.0  0.75

pair_coeff  2  2   mdpd  -23.0  25.0  4.5  1.0  0.75
pair_coeff  3  3   mdpd  -50.0  25.0  4.5  1.0  0.75
pair_coeff  2  3   mdpd  -26.0  25.0  4.5  1.0  0.75
pair_coeff  1  3   mdpd  -51.0  25.0  4.5  1.0  0.75
pair_coeff  1  1   mdpd  -37.0  25.0  4.5  1.0  0.75
pair_coeff  1  2   mdpd  -30.0  25.0  4.5  1.0  0.75


dump 20 all atom 100 min2.lammpstrj

neigh_modify every 1 delay 0 check yes
min_style cg
minimize 0 0 1000 10000

fix         mvv     all mvv/dpd 0.65

compute             mythermo all temp
thermo              100
thermo_modify       temp mythermo
thermo_modify       flush yes

#thermo_modify	 lost ignore lost/bond ignore

timestep 0.01

dump 1 membrane atom 1000 mem2.lammpstrj
dump 2 all atom 100 all2.lammpstrj

run 3000000
