units lj
dimension 3
boundary p p p

atom_style hybrid angle mdpd
neighbor 0.3 bin
neigh_modify delay 4 every 2
comm_modify vel yes

read_data initial.data

replicate 2 1 1 

#fix 1 all property/atom d_meso/rho
#compute 10 all sph/rho/atom

group 1 type 1
group 2 type 2
group water type 3
group membrane type 1:2
group all union water membrane

group aa union 1 2 water
set group aa sph/rho 6


bond_style harmonic
bond_coeff 1 400 0.64
bond_coeff 2 400 0.64

angle_style harmonic
angle_coeff 1 100 160
angle_coeff 2 100 160

pair_style hybrid/overlay mdpd/rhosum mdpd 1.0 1.0 65689
pair_coeff  *  *   mdpd/rhosum  0.75

pair_coeff  1  1   mdpd  -19.0  25.0  12  1.0  0.75
pair_coeff  1  2   mdpd  -5.98  25.0  12  1.0  0.75
pair_coeff  1  3   mdpd  -32.18 25.0  12  1.0  0.75
pair_coeff  2  2   mdpd  -22.0  25.0  12  1.0  0.75
pair_coeff  2  3   mdpd  -27.0  25.0  12  1.0  0.75
pair_coeff  3  3   mdpd  -40.0  25.0  12  1.0  0.75

dump 20 all atom 100 min-l.lammpstrj

neigh_modify every 1 delay 0 check yes

fix         mvv     all mvv/dpd 0.65

compute             mythermo all temp
thermo              100
thermo_modify       temp mythermo
thermo_modify       flush yes

thermo_modify	 lost ignore lost/bond ignore

timestep 0.01

dump 2 all atom 100 all-rep.lammpstrj

run 4000

